spring.application.name=edu
server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://hw.bbjc.cc:5432/bbjczdb?currentSchema=myschema
spring.datasource.username=bbjcz
spring.datasource.password=Bbjcz@7891
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=SNAKE_CASE
mybatis.configuration.map-underscore-to-camel-case=true
